### ISSUE TITLE
[Feature Request] Change the way drop down menus work (auto highlight on cursor focus)

### ISSUE THREAD

**Issue by mm2270** [IBM/mac-ibm-notifications#110]
**Is your feature request related to a problem? Please describe.**
I'm not sure what the correct term for this is, but one thing that kind of irritates me about IBM Notifier's drop down menus is how the drop down items in a menu do not "highlight" on mouse over. You have to click two times to select any item in the menu, which is completely normal, but there is no visual feedback of which item you are actually selecting until you click the second time. This creates a kind of frustrating experience when using the drop down menus.

**Describe the solution you'd like**
I'd like to see the method of how drop downs are drawn and operate to auto highlight on mouse over. I know this is possible because other dialog tools can do this already. I took a short video of IBM Notifier's behavior versus behavior from swiftDialog to show the difference.

**IBM Notifier**
![IBMNotifier_dropdown_AdobeExpress](https://user-images.githubusercontent.com/3653600/183516612-06c7d618-7cc7-4842-979c-8e3d6325a1aa.gif)

**swiftDialog**
![swiftDialog_dropdown_AdobeExpress](https://user-images.githubusercontent.com/3653600/183516683-8c7d4218-6633-411d-8e1a-9b9066c7173e.gif)

**Describe alternatives you've considered**
None. I'm not able to affect this built in behavior.

Any chance that this can be updated to the other behavior in some future release? It's really a more user friendly way to draw the drop down menus in my opinion. Thanks for considering!

**Comment by SMartorelli** [comment]
Hi @mm2270 the planned migration from AppKit to SwiftUI should help us in making dropdown looks more reactive like you suggested. Sadly the actually AppKit component doesn't provide us much way to replicate this behaviour. I'll track this FR for our post migration work.

**Comment by mm2270** [comment]
Ok, thanks for that update.

**Comment by seanism** [comment]
You also need to click the arrow on the right versus the entire textbox.  Not sure if this is a bug or the way it has to be.

**Comment by SMartorelli** [comment]
Yes this is how it behave the native AppKit component, a more modern approach is provided by SwiftUI that we're going to adopt in the near future 💪
