### ISSUE TITLE
Pre-select Dropdown option

### ISSUE THREAD

**Issue by staze** [IBM/mac-ibm-notifications#111]
Would love to see, if it doesn't exist already, a way to pre-select a value from a Dropdown. My use case being, we're trying to make an easy GUI for users to change their office location when they move offices. So it would be nice to grab the current values from Jamf (or where ever), and have that set as the current Dropdown value. 

I was thinking just sorting that to the top of the list, but it looks like Dropdowns just default to no selection. 

Thanks!

**Comment by mm2270** [comment]
You can do this actually. From the Accessory View Payloads page for drop downs
```
/selected INDEX integer index (first item is 0) which will select the related item from the passed array;
```
The parameters that define your drop down menu can use the above to "select" one of the items by default. You *do* have to know the array index value of what you want to be selected by default when the popup appears though.

**Comment by staze** [comment]
That's awesome... Thank you sir!
