### ISSUE TITLE
[BUG] App icon (default_icon) is not crisp

### ISSUE THREAD

**Issue by kryptonit1** [IBM/mac-ibm-notifications#116]
**Describe the bug**
This is not really a bug, but I would not consider it a feature either. When you rebrand IBM Notifier with your own app icon it becomes clear that the app icon is not very crisp. I first thought that this was due to some error on my part, but it seems like it's not.

This is how my custom app icon looks like in the pop-up UI when an icon path has not been specified:
<img width="641" alt="default_icon" src="https://user-images.githubusercontent.com/33235315/186593083-49653d4c-3da0-4a5f-b1da-b142286f8a64.png">

This is how the app icon looks like when I create and specify a separate ICNS-file that I use in the pop-up UI:
<img width="641" alt="separately_created_icns" src="https://user-images.githubusercontent.com/33235315/186593098-4ce6cac2-3a37-4fbb-9f01-bef963d4e480.png">

I think the difference in crispness is due to the lack of different icon sizes for the default_icon for the pop-up UI in the Xcode project:
![xcode_default_icon](https://user-images.githubusercontent.com/33235315/186593828-de2ca7bd-66c2-44be-88a1-f3e1c4832e5a.png)

This is not a problem when you push out banners or alerts since it seems like it might be utilising the AppIcon asset under the Notification Agent in the Xcode project which contains more icon sizes:
![xcode_notification_icons](https://user-images.githubusercontent.com/33235315/186594133-1aa728ea-57e5-4292-b311-9face0ac1b40.png)

**To Reproduce**
1. Rebrand IBM Notifier with a custom icon using the instructions in the wiki.
2. Push out a pop-up notification and take a screenshot of the pop-up.
3. Push out a pop-up notification with an icon_path specified. You can use any default macOS ICNS icon under /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources. Take a screenshot of the pop-up.
4. Compare the difference in crispness between the icons.

It's possible to work around this by specifying an icon path to a separately created ICNS, but it would be nice if the default_icon contained more sizes so that you would not have to create a separate ICNS in order for the icon to look more crisp.

**Expected behavior**
The app icon should look as crisp as the default macOS icons.

**Screenshots**
Please see above.

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Project version: 2.8.0

**Additional context**
N/A

**Comment by SMartorelli** [comment]
Hi @kryptonit1 I know what you mean and I also observed this. Tbh I didn't noticed the difference between custom path icons and the default one without your example. We'll work to improve this in the next iteration!

**Comment by kryptonit1** [comment]
Thank you for your quick reply as always! :)

I think since the IBM Notifier default icon is black you don't see the difference as much as when you have a custom icon using other colors.
