### ISSUE TITLE
[BUG] Can we have separate app icon for DARK mode and Light Mode

### ISSUE THREAD

**Issue by SohailUrRahmanGit** [IBM/mac-ibm-notifications#118]
I am not sure if we can set Dark mode/ Light mode app icon for the mac Application. Can you please help me on this

**Comment by SMartorelli** [comment]
Hi @SohailUrRahmanGit with App Icon you mean the Icon of the app itself in the Application folder or the default pop-up icon that appear on the dialog?

**Comment by SohailUrRahmanGit** [comment]
Both the scenarios

**Comment by SMartorelli** [comment]
You can already define 2 different pop-up icon based on system appearance as you can see 
<img width="961" alt="Dark_Light_Appearance" src="https://user-images.githubusercontent.com/23209655/187369111-c64f924a-6e9f-45e4-b903-78e5cab00c6b.png">
Mind that when you rebrand the app.
The App Icon can't have 2 different version based on system appearance. It must be consistent.

**Comment by SohailUrRahmanGit** [comment]
Thank you for the. pop-up icon information , I would like to set App Icon too in Dark mode and light mode. I have done the feature in iOS but not sure if mac supports Setting up two different app icon

**Comment by SMartorelli** [comment]
Hi @SohailUrRahmanGit no this doesn't looks to be possible for macOS Applications.
