### ISSUE TITLE
Feature Request for Secure user input

### ISSUE THREAD

**Issue by tkimpton** [IBM/mac-ibm-notifications#124]
Im currently using cocoaDialog when im needing to prompt the logged in user for their password to pass that on for other variables and automations. Would it be possible to add this to the product?

**Comment by SMartorelli** [comment]
Hi @tkimpton, this feature is already available in IBM Notifier using a `secureinput` accessory view. Please refer to the [Usage](https://github.com/IBM/mac-ibm-notifications/wiki/Usage) and in details to the [Pop-up UI Accessory View](https://github.com/IBM/mac-ibm-notifications/wiki/Pop-up-UI-Accessory-Views) wiki pages.
