### ISSUE TITLE
[BUG] Markdown numbered list behaviour in subtitle element

### ISSUE THREAD

**Issue by mrmte** [IBM/mac-ibm-notifications#125]
**Describe the bug**
With a pop up type dialog and subtitle if you wish to show numbered items like
1. This is example 1
2.  This is example 2

What actually shows is this 

1.       This is example 1
2.  This is example 2

The first numbered item has a strange tabed paragraph indent

**To Reproduce**
1. create a script

#!/bin/bash
IBM_NOTIFIER="/usr/local/bin/IBM Notifier.app/Contents/MacOS/IBM Notifier"

$IBM_NOTIFIER -type popup -title "Example" -icon_path /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns -always_on_top -silent -bar_title "System Maintenance" -subtitle "System Maintenance is required to ensure your machine is security compliant

1. This is example 1

2. This is example 2

For more information see internal KB XXX" -main_button_label "Proceed"

**Expected behavior**
Expected behaviour is to have the text aligned correctly but it is not 

**Screenshots**

<img width="597" alt="Screenshot 2022-09-13 at 10 49 56" src="https://user-images.githubusercontent.com/2095960/189871772-15876d9d-a57b-4d6f-becf-b23b9a995f11.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11] macOS 13
 - Project version [e.g. 1.0.0]

**Additional context**

**Comment by vc5047** [comment]
I see this on Monterey as well

**Comment by SMartorelli** [comment]
Hi @mrmte @vc5047 the correct format to show numbered list in this case should be:
```
$IBM_NOTIFIER -type popup -title "Example" -icon_path /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns -always_on_top -silent -bar_title "System Maintenance" -subtitle "System Maintenance is required to ensure your machine is security compliant

1. This is example 1

1. This is example 2

For more information see internal KB XXX" -main_button_label "Proceed"
```
Hope this will help 👍
