### ISSUE TITLE
[Feature Request] Custom button labels in Onboarding UI

### ISSUE THREAD

**Issue by iespob** [IBM/mac-ibm-notifications#131]
**Is your feature request related to a problem? Please describe.**
The Onboarding workflow is awesome, thank you! 
though it is limited for many situations as there is no ability to change the button labels on the last window.

**Describe the solution you'd like**
Be able to use button labels on the last window so we can change the wording if needed.

**Describe alternatives you've considered**
In this instance we wold like the user to acknowledge certain text, we could change the text to say "press close to acknowledge" but we also want a button to allow the user to exit without acknowledgement, at the moment they only have the option to close or go back a window.

There is already a [feature request](https://github.com/IBM/mac-ibm-notifications/issues/123) for adding a tertiary button, if the label on the tertiary button can be changed there would be no need for this request.

**Comment by SMartorelli** [comment]
Thanks for this FR. Yes the label of the future tertiary button on the onboarding UI will be customisable but I think that we can still work to make customisable also the two predefined ones.

**Comment by iespob** [comment]
Awesome, having more flexibility with all the buttons will definitely be beneficial, thanks.
