### ISSUE TITLE
[Feature Request] Adjustable height and width for both Onboarding UI and Popup UI

### ISSUE THREAD

**Issue by Alitejawi** [IBM/mac-ibm-notifications#133]
**Is your feature request related to a problem? Please describe.**
The default window for the onboarding UI and the popup UI is covering a portion of a screen, but when I include a video, the video should be able to be played in a larger surface area. 

**Describe the solution you'd like**
Ideally make the onboarding UI and the popup UI adjustable in height x width. 

**Describe alternatives you've considered**
A higher resolution video does not result in a clearer crisper view of the video being played in the onboarding UI and the popup UI.

**Comment by SMartorelli** [comment]
Hi @Alitejawi we'll work on an adjustable height/width only for pop-up UI for some scenarios. We don't think it might be useful on the Onboarding UI. We want to respect as much as we can Apple HIG. Of course for video accessory views a bigger frame might be helpful.
