### ISSUE TITLE
[BUG] Quitting IBM Notifier returns 0 or main button pressed

### ISSUE THREAD

**Issue by rrhiralal** [IBM/mac-ibm-notifications#138]
**Describe the bug**
Quitting IBM Notifier, either via CMD+Q or via activity monitor, returns 0 or main button pressed

**To Reproduce**
Run IBM notifier from terminal, hit cmd+Q or quit via activity monitor
Monitor output, it will return 0

**Expected behavior**
An action like this should return something other than a success. Ideally an error with a unique error code corresponding to that action.

Additionally, it would be good to have the ability to configure settings to allow or block the ability to use cmd+Q. From an admin perspective, this would be helpful and avoid users skirting policies that rely on the notifier prompts

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13
 - Project version: 2.9.1

**Additional context**

**Comment by marcusheBG** [comment]
Hi 2nd'ing the request to block command Q

We tried adding custom System Preferences Keyboard app shortcuts for "Quit" and "Quit IBM Notifier" (which can also be done command line) but no success.

Thank you so much.

**Comment by porkcharsui** [comment]
Rather than blocking the COMMAND + Q shortcut in IBM Notifier, using non-zero return code that denotes the notification was closed would suffice.

Today's behavior of exit code `0` for quit events AND main button presses makes it impossible for the calling script to understand what actually occurred!

**Comment by SMartorelli** [comment]
Yes @porkcharsui the plan for this issue is to return the code "239: User dismissed the popup/banner/onboarding UI" instead of 0 when CMD+Q shortcut is used.
