### ISSUE TITLE
WIki page for guiding admin on how to sign and notarize the app

### ISSUE THREAD

**Issue by Grant8907** [IBM/mac-ibm-notifications#14]
**Is your feature request related to a problem? Please describe.**
macOS security settings require apps to be signed and notarized.   How can we deploy this app signed and notarized?

**Describe the solution you'd like**
I'd like to be able to easily sign and notarize this code.

**Comment by SMartorelli** [comment]
Wiki page now available here: https://github.com/IBM/mac-ibm-notifications/wiki/Archive,-sign-and-notarize-the-app
