### ISSUE TITLE
[BUG] cannot use dropdown -accessory_view_payload with -accessory_view_payload -timer 

### ISSUE THREAD

**Issue by tkimpton** [IBM/mac-ibm-notifications#149]
**Describe the bug**
Using a dropdown -accessory_view_payload showing and also trying to use -accessory_view_payload "Time left: %@" -timeout. I need to have a timeout because users will sit at the dialog options and do nothing. I need to be able to show the count down time out. It appears you cannot use -accessory_view_payload -timer along with -

**To Reproduce**
1. replace variable with path to where you have it installed
2. create a script with the contents

"$IBM_NOTIFIER" -type popup -icon_path "$SN_IMAGE" -always_on_top -silent -bar_title "OS Upgrade to macOS Ventura version $VERSION" -subtitle "The upgrade will take approximately 45 - 150 minutes at which time you cannot use the machine. Before you begin the upgrade, backup and save your work to OneDrive. 

Be sure to plug in your charger and are connected to reliable WiFi, that will not change during the upgrade.

Please choose an install time from the above deferral options and click \"Defer\".

If you wish to apply the upgrade right away, save all your work, close all applications and click \"Upgrade Now\"."  -accessory_view_type dropdown -accessory_view_payload "/list 1 Hour\n2 Hours\n4 Hours\n6 Hours\n8 Hours/selected 0" -accessory_view_type timer "Time left: %@" -timeout 3600 -main_button_label "Defer" -secondary_button_label "Update Now"

**Expected behavior**
expect to see the time left % but nothing shows up

the only thing that does work is below but it doesnt show the % left

"$IBM_NOTIFIER" -type popup -icon_path "$SN_IMAGE" -always_on_top -silent -bar_title "OS Upgrade to macOS Ventura version $VERSION" -subtitle "The upgrade will take approximately 45 - 150 minutes at which time you cannot use the machine. Before you begin the upgrade, backup and save your work to OneDrive. 

Be sure to plug in your charger and are connected to reliable WiFi, that will not change during the upgrade.

Please choose an install time from the above deferral options and click \"Defer\".

If you wish to apply the upgrade right away, save all your work, close all applications and click \"Upgrade Now\"."  -accessory_view_type dropdown -accessory_view_payload "/list 1 Hour\n2 Hours\n4 Hours\n6 Hours\n8 Hours/selected 0" -timeout 3600 -main_button_label "Defer" -secondary_button_label "Update Now"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11]
 - Project version [e.g. 1.0.0]

**Additional conte
<img width="597" alt="Screenshot 2023-02-17 at 10 11 37" src="https://user-images.githubusercontent.com/2095960/219617898-48fd0672-4239-4253-8eb0-8a476f6b168c.png">
xt**

**Comment by SMartorelli** [comment]
Hi @tkimpton looks like you have some arguments missing in your prompt (-secondary_accessory_view_type and -secondary_accessory_view_payload) and that's why the secondary timer accessory view doesn't shows up.
Try with these arguments to configure you accessory views:
`-accessory_view_type dropdown -accessory_view_payload "/list 1 Hour\n2 Hours\n4 Hours\n6 Hours\n8 Hours /selected 0" -secondary_accessory_view_type timer -secondary_accessory_view_payload "Time left: %@" -timeout 3600`

**Comment by SMartorelli** [comment]
@tkimpton can you please confirm that the solution worked? I will close the issue in 48hrs

**Comment by SMartorelli** [comment]
Closing the issue since I didn't received any feedback from the reporter.

**Comment by tkimpton** [comment]
Brilliant, thanks very much it works
