### ISSUE TITLE
[BUG] Notifier does not focus itself when launched by Jamf Binary

### ISSUE THREAD

**Issue by S-Groening** [IBM/mac-ibm-notifications#157]
**Describe the bug**
I've created a shell script to open IBM Notifier and perform a series of events upon clicking the main button.

On opening the same script from Self Service, IBM Notifier correctly assumes focus and brings itself to be front most app, but when launched with /usr/local/jamf/bin/jamf policy -event <trigger> this does not happen and IBM Notifier keeps in the background.

It seems to always be this way when executed as above, but execution by recurring check in triggers work as expected. 

**To reproduce:**

Create a script on your Jamf server or Jamf Cloud instance and have it open IBM Notifier like this:

```
#!/bin/bash

# Variables
NOTIFIER="/usr/local/bin/IBM Notifier.app/Contents/MacOS/IBM Notifier"
TITLE="IBM Notifier Test Script"
SUBTITLE="This will be your subtitle."
IMAGE_URL="https://your.server.com/image.png"

userResponse(){
	BUTTON=$("${NOTIFIER}" \
		-type popup \
		-title "${TITLE}" \
		-subtitle "${SUBTITLE}" \
		-accessory_view_type "image" \
		-accessory_view_payload "${IMAGE_URL}" \
		-main_button_label "Continue" \
		-secondary_button_label "Cancel")

	# Return exit code
	/bin/echo "$?"
}

# Script logic
RESPONSE=$(userResponse)

if [[ ${RESPONSE} -eq 0 ]]; then
	/bin/echo "Do stuff..."
else
	exit 1
fi

exit 0 
``` 

OS: macOS 13.3.1
Jamf Pro: 10.45.1
IBM Notifier: v. 2.9.1

**Comment by SMartorelli** [comment]
Hi @S-Groening 👋 I'm pretty sure this happens because when you trigger the policy from terminal Jamf verbosity let the terminal regain focus after IBM Notifier kicked in. You can test it by triggering the test policy at checkin and see if the behaviour persist.

**Comment by SMartorelli** [comment]
Yeah this is not an issue with IBM Notifier itself. It's just a behaviour you see while testing it with some manual policy execution. I'm going to close it as it's out of scope for IBM Notifier.
