### ISSUE TITLE
[BUG] -accessory_view_payload "Time left: %@"  not working with  -accessory_view_type html

### ISSUE THREAD

**Issue by mrmte** [IBM/mac-ibm-notifications#161]
**Describe the bug**
im trying to get the -accessory_view_payload "Time left: %@" working with a popup using -accessory_view_type html to show the count down timer. Is this possible? the timeout does work it just doesn't show the time left 

**To Reproduce**
`"/usr/local/bin/IBM Notifier.app/Contents/MacOS/IBM Notifier" -type popup -bar_title "bar title" -always_on_top -silent -accessory_view_type timer -accessory_view_payload "Time left: %@" -timeout "20" -main_button_label "I Understand" -accessory_view_type html -accessory_view_payload "<h1>Heading title</h1><span style=\"color: #ff0000\">Important Notes - Must Read</span><br><br>line 1<br><br>line 2<br>line 3<br>line 4<br>line 5<br>line 6<br>line 7<br><br>line 8<br>line 9<br>line 10"`

**Expected behaviour**
the countdown timer to show

**Screenshots**

<img width="597" alt="Screenshot 2023-05-16 at 09 54 21" src="https://github.com/IBM/mac-ibm-notifications/assets/2095960/6a89abd3-28f2-447a-8976-0dd6009d0806">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 13.3.1]
 - Project version 2.9.1

**Additional context**
working on a workflow which requires a reboot so it is essential.

**Comment by SMartorelli** [comment]
Hi @mrmte you can use a maximum of two accessory views for popup dialog leveraging -accessory_view_type/payload and -secondary_accessory_view_type/payload. So your example should look like:
`"/usr/local/bin/IBM Notifier.app/Contents/MacOS/IBM Notifier" -type popup -bar_title "bar title" -always_on_top -silent -accessory_view_type timer -accessory_view_payload "Time left: %@" -timeout "20" -main_button_label "I Understand" -secondary_accessory_view_type html -secondary_accessory_view_payload "<h1>Heading title</h1><span style=\"color: #ff0000\">Important Notes - Must Read</span><br><br>line 1<br><br>line 2<br>line 3<br>line 4<br>line 5<br>line 6<br>line 7<br><br>line 8<br>line 9<br>line 10"`

**Comment by mrmte** [comment]
Brilliant! Thanks very much :)
