### ISSUE TITLE
Rename of the app

### ISSUE THREAD

**Issue by GenoMyb** [IBM/mac-ibm-notifications#17]
**Describe the solution you'd like**
I would like to rename the application from Mac@IBM to Mac@{something_else}
are there any documentation?

**Comment by jvalentik** [comment]
Hi @GenoMyb we're working on a detailed Wiki page dedicated to custom branding, hoping to have it live as early as next week. Issue for this is already created [here](https://github.com/IBM/mac-ibm-notifications/issues/15), therefore closing this.

**Comment by GenoMyb** [comment]
Hi Team.

Thank you , and thank you for the app

Kind regards
