### ISSUE TITLE
Allow selection of pop-up position on screen

### ISSUE THREAD

**Issue by GenoMyb** [IBM/mac-ibm-notifications#18]
**Describe the solution you'd like**
Is it possible to move the popup window 
eg 
--Centre
--bottomleft 
--topleft
--topright
--bottomright

**Comment by SMartorelli** [comment]
Hi Eugene,
thanks for your request. We're already working on this feature for pop-up UIs but we don't have any ETA yet. 
I hope you don't mind if I rename this issue to better describe the FR. You can follow the updates of the future related deployment from here.
Thanks

**Comment by GenoMyb** [comment]
Don’t mind at all , thank you

**Comment by SMartorelli** [comment]
This FR is currently in QA Process
