### ISSUE TITLE
[BUG] IBM_Notifier_Onboarding.plist not created

### ISSUE THREAD

**Issue by kaylakeman** [IBM/mac-ibm-notifications#186]
**Describe the bug**
I hoped #170 would have resolved the issue, but IBM_Notifier_Onboarding.plist is not created in version 3.0.2.

**To Reproduce**
1. Create an onboarding flow
2. Do a walkthrough with a checkbox in it
3. Finish it
4. No file is created

**Expected behavior**
I expect IBM_Notifier_Onboarding.plist to be created

**Desktop (please complete the following information):**
 - OS: [macOS 13.3.1]
 - Project version [3.0.2]

**Comment by SMartorelli** [comment]
Hi @kaylakeman you're right. The file is wrongly located in the `.mainotifications` user folder. I'm going to release v3.0.3 with the fix in a bit. Thanks for the report
