### ISSUE TITLE
[DOC] Instructions for archiving, signing and notarizing the app needs to be updated

### ISSUE THREAD

**Issue by kryptonit1** [IBM/mac-ibm-notifications#192]
**Describe the bug**
The instructions for [archiving, signing and notarizing the app](https://github.com/IBM/mac-ibm-notifications/wiki/Archive,-sign-and-notarize-the-app) does not match the steps in the latest version of Xcode.

**To Reproduce**
Try to perform steps 2-10 in the guide in Xcode 15.

**Comment by SMartorelli** [comment]
Thanks for catching this, we will update the wiki page!

**Comment by SMartorelli** [comment]
Documentation has been updated. 
https://github.com/IBM/mac-ibm-notifications/wiki/Archive,-sign-and-notarize-the-app
