### ISSUE TITLE
[BUG] Pop-up UI usage of `-unmovable` breaks `-always-on-top` and `-position` options.

### ISSUE THREAD

**Issue by Macjutsu** [IBM/mac-ibm-notifications#193]
**Describe the bug**
Pop-up UI usage of `-unmovable` breaks `-always-on-top` and `-position` options.

**To Reproduce**
```
IBM\ Notifier.app/Contents/MacOS/IBM\ Notifier -type popup -bar_title Test -subtitle Test -unmovable -always_on_top -position top_right
```
**Screenshots**

<img width="1140" alt="SCR-20231022-mmoz" src="https://github.com/IBM/mac-ibm-notifications/assets/86124561/efdd06ee-c9fc-4ffb-957c-c25d698a6072">

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Project version: 3.0.3

**Comment by SMartorelli** [comment]
Hi @Macjutsu, thanks for reporting this! I just reproduced it. I've also noticed that by changing the order of the arguments they got parsed correctly. This should work as temp workaround until I don't fix the main cause.
`IBM\ Notifier.app/Contents/MacOS/IBM\ Notifier -type popup -bar_title Test -subtitle Test -unmovable -position top_right  -always_on_top`

**Comment by Macjutsu** [comment]
Thank you! Fortunately the way I've implemented this in `super` was an easy fix. The v4.0.0 release of `super` out this week will not be affected by this issue!
