### ISSUE TITLE
Trying to get the user chosen from a list

### ISSUE THREAD

**Issue by mrmte** [IBM/mac-ibm-notifications#203]
**Describe the bug**
trying to get the user selected from a list

**To Reproduce**
`#!/bin/bash
IBM_NOTIFIER="/usr/local/bin/IBM Notifier.app/Contents/MacOS/IBM Notifier"
USER_LIST=($( dscl . -list /Users | grep -v "^_" | grep -iwv "^daemon" | grep -iwv "^nobody" | grep -wv "^root" | grep -wv "^it" | grep -wv "^userbackup" | grep -wv "^temp_jssroot" ))

USER_SELECTION=($("$IBM_NOTIFIER" -type popup -bar_title "$TITLE" -icon_path "$SN_IMAGE" -always_on_top -silent -subtitle "Choose the account you wish to create a new login keychain:" -accessory_view_type dropdown -accessory_view_payload "/list "${USER_LIST[@]}" /selected 0"))
echo $?
exit 0`

**Expected behavior**
I thought it would echo the user chosen but it returns 0

**Screenshots**

<img width="632" alt="Screenshot 2024-01-18 at 13 46 18" src="https://github.com/IBM/mac-ibm-notifications/assets/2095960/dc257521-edef-4134-b367-d3ae218963bd">
<img width="682" alt="Screenshot 2024-01-18 at 13 46 24" src="https://github.com/IBM/mac-ibm-notifications/assets/2095960/c0ae6cb7-82b0-4d22-812f-3aa1e8304a80">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.2.1]
 - Project version [e.g. 3.0.3]

**Additional context**

**Comment by SMartorelli** [comment]
Hi @mrmte. Yes the accessory view return the index of the selected item in the source array. Just using `echo "${USER_LIST[$?]}"` should work for you.

**Comment by mrmte** [comment]
brilliant thanks very much :)
