### ISSUE TITLE
Guidelines to implement and deploy the SUPERMAN for the very first time

### ISSUE THREAD

**Issue by CSK369** [IBM/mac-ibm-notifications#225]
Hi,
We are looking for some Guidelines to implement and deploy the SUPERMAN for the very first time
Can anyone provide the guidelines, whether we need a configuration profile to be deployed first or policy. 
please let us know how one can proceed for the very first time

**Comment by SMartorelli** [comment]
Hi @CSK369 thanks for reaching out. I suggest you to open a Discussion thread on the [SUPERMAN](https://github.com/Macjutsu/super) repository for this. This is the IBM Notifier repo.
