### ISSUE TITLE
payload type video for youtube videos do not load in popup or onboarding UI

### ISSUE THREAD

**Issue by K1jaff** [IBM/mac-ibm-notifications#31]
**Describe the bug**
When using a youtube weblink for the video payload the UI loads without the video and returns the error: Unable to load video resolution from https://www.youtube.com/watch?v=dQw4w9WgXcQ

2021-05-24 15:40:23.475 Mac@IBM Notifications[90265:1957314] *** Assertion failure in -[NSLayoutConstraint _setSymbolicConstant:constant:symbolicConstantMultiplier:], NSLayoutConstraint.m:670
2021-05-24 15:40:23.485 Mac@IBM Notifications[90265:1957314] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSLayoutConstraint constant is not finite!  That's illegal.  constant:nan firstAnchor:<NSLayoutDimension:0x7ff48c7b7b60 "AVPlayerView:0x7ff48d008a00.height"> secondAnchor:(null)'

**To Reproduce**
 run mac-ibm-notifications type popup or onboard with video and payload of youtube url

 i.e. ./"Mac@IBM Notifications" -type popup -title "Test title" -subtitle "Test subtitle" -accessory_view_type video -accessory_view_payload "https://www.youtube.com/watch?v=dQw4w9WgXcQ" -main_button_label "OK"

~/Applications/Mac@IBM\ Notifications.app/Contents/MacOS/Mac@IBM\ Notifications -type onboarding -payload "{\"pages\":[{\"title\":\"First page's title\",\"subtitle\":\"First page's subtitle\",\"body\":\"First page's body\",\"mediaType\":\"video\",\"mediaPayload\":\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"}]}"

**Expected behavior**
Video to be loaded in frame

**Desktop (please complete the following information):**
 - OS: testing done on macOS 11.3.1
 - Project version 2.1.0 build24

**Comment by SMartorelli** [comment]
Hi @K1jaff, Mac@IBM Notifications only supports direct link to the media file since it uses the native macOS Player and doesn't integrate any third party player.

**Comment by K1jaff** [comment]
Ah okay may need to update the example for pop-up as it has youtube link in it. Can confirm direct links are working just fine.

To display a video style pop-up pass -accessory_view_type video parameter.

Video has a mandatory -accessory_view_payload parameter as direct URL of the video or absolute path to the video file as quoted text. If video path or URL does not exist or is incorrect, error message is printed.

Error message when video is incorrect:
Unable to load video from https://www.youtube.com/watch\?v\=r7E1TJ1HtM0

Example command:
./"Mac@IBM Notifications" -type popup -title "Test title" -subtitle "Test subtitle" -accessory_view_type video -accessory_view_payload "/Users/johny/Documents/video.mov" -main_button_label "OK"

**Comment by SMartorelli** [comment]
Thanks for the report! Will update docs asap.
