### ISSUE TITLE
Add an icon to notification banner/alert by argument

### ISSUE THREAD

**Issue by mallej** [IBM/mac-ibm-notifications#44]
**Is your feature request related to a problem? Please describe.**
I´m switching from Yo to Mac-ibm-motifications and sorely miss the ability to include icons in notifications.

**Describe the solution you'd like**
The --icon argument from https://github.com/sheagcraig/yo 

**Additional context**
as you can see in the screenshot, I used the icon function of Yo to indicate to the end user which app was installed with Munki.
![Screenshot 2021-09-16 at 12 49 53](https://user-images.githubusercontent.com/124450/133648727-dd7e8f52-901b-43d3-8f07-5004fbb6c539.png)
.

**Comment by SMartorelli** [comment]
Hi @mallej, thanks for suggesting new features. We'll take care of it asap.

**Comment by kylejericson** [comment]
How do you use this icon option when running as a Notification banner/alert?

**Comment by SMartorelli** [comment]
Hi @kylejericson, this FR has not been implemented yet

**Comment by kylejericson** [comment]
In the meantime if you wanted a custom icon could you edit the xcode project with a custom icons? If so what image sizes would you need?

**Comment by SMartorelli** [comment]
Do you mean how to change the left icon for the banner/alert? That icon is inherited from the main app icon and so only rebranding the app you can customize it. To do so read more here: https://github.com/IBM/mac-ibm-notifications/wiki/Rebranding-the-application

**Comment by kylejericson** [comment]
Thanks so much didn't see this.
