### ISSUE TITLE
cannot open app url

### ISSUE THREAD

**Issue by mallej** [IBM/mac-ibm-notifications#45]
**Describe the bug**
using an app path as url does not open the app

**To Reproduce**
~/IBM\ Notifier.app/Contents/MacOS/IBM\ Notifier -type alert -title "Test title" -main_button_label "Main button" -main_button_cta_type link -main_button_cta_payload "/Applications/Safari.app" --v

**Expected behavior**
 a click on the main button should open the app

**Desktop (please complete the following information):**
 - OS: macOS 11.6 & 11.5.2

**Comment by AndrewWCarson** [comment]
@mallej I think you need a protocol included in the payload. In this case, using "file://" should work as the system knows how to open local files of that type.

For example,
`~/IBM\ Notifier.app/Contents/MacOS/IBM\ Notifier -type alert -title "Test title" -main_button_label "Main button" -main_button_cta_type link -main_button_cta_payload "file:///Applications/Safari.app" --v`

worked for me.

**Comment by mallej** [comment]
worked for me, too.
thanks for clarification.
