### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mm2270** [IBM/mac-ibm-notifications#51]
I've been playing around with IBM Notifier since hearing about it at JNUC 2021, and I really like it.

But I'm seeing one issue that may be a bug, kind of hard to tell. But I'm unable to get the tertiary button to show up in any popup style window. I first started to see it in a script I'm working on around using IBM Notifier. But then I ran a very simple command direct from Terminal and am seeing the same issue. Here's what I'm trying:

```
~/Downloads/IBM\ Notifier.app/Contents/MacOS/IBM\ Notifier -type popup -title "Title" -main_button_label "Install Now" -secondary_button_label "Defer" -tertiary_button_label "Delay"
```
This is what it produces:

<img width="641" alt="Screen Shot 2021-10-21 at 1 32 24 PM" src="https://user-images.githubusercontent.com/3653600/138328238-178264f7-c027-4f2e-8bc0-47ae19eca7ce.png">

That 3rd button never shows up. Does this actually work with the popup style, or am I doing something wrong? The Wiki indicates it does work with the popup style, but everything I've tried so far hasn't been able to get it show up.

OS: macOS 11.6
IBM Notifier version: 2.3.2

**Comment by SMartorelli** [comment]
Hello @mm2270, the tertiary button is not destructive for the pop-up ui and so you need to define a scope for it using tertiary_button_cta_type and tertiary_button_cta_payload arguments. As you can see from the syntactic rules in the wiki if you don't need the tertiary button to do anything you can set exitlink as cta type and leave empty the payload.

Ex: -tertiary_button_label "Tertiary" -tertiary_button_cta_type exitlink -tertiary_button_cta_payload ""

Hope this will solve your issue!
