### ISSUE TITLE
Xcode 13.1 Package Error

### ISSUE THREAD

**Issue by SohailUrRahmanGit** [IBM/mac-ibm-notifications#92]
Hi Team

Getting this Error in the latest code base. Unable to Run the application. Can you guys help me on this

<img width="1130" alt="Screenshot 2022-06-09 at 10 25 14 AM" src="https://user-images.githubusercontent.com/22540497/172767428-d2bf0ab2-1f97-4ed0-8f09-37f6f84b1365.png">

<img width="501" alt="Screenshot 2022-06-09 at 10 32 53 AM" src="https://user-images.githubusercontent.com/22540497/172768742-d128b9b5-99c4-4689-bae3-bbba7a5a0864.png">

**Comment by SMartorelli** [comment]
Hi @SohailUrRahmanGit try these steps:
1. Reset Package Caches (In Xcode -> File -> Packages -> Reset Package Caches)
2. Clean build folder (In Xcode -> Product -> Clean Build Folder)
3. Update to Last Package Versions (In Xcode -> File -> Packages -> Update to Last Package Versions)
Let me know if this solved your issue.

**Comment by SohailUrRahmanGit** [comment]
I have tried the above steps doesnt seem to work either.

**Comment by SMartorelli** [comment]
Have you tried to delete `mac-ibm-notifications/Notification\ Agent.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` like suggested by the error message and resolve the packages again?
